<?php

namespace App\Services\Domains;

use App\Models\Domain;
use App\Models\DomainProvider;
use App\Models\DomainTld;
use App\Models\Invoice;
use App\Models\Order;
use App\Services\Billing\InvoiceSettlementService;
use Carbon\Carbon;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Str;

class DomainRenewalService
{
    public function prepareRenewalCheckout(Domain $domain, int $years = 1, bool $autoGenerated = false): array
    {
        $domain->loadMissing('client');

        $existingInvoice = $this->findPendingRenewalInvoice($domain);
        if ($existingInvoice instanceof Invoice) {
            return [
                'invoice' => $existingInvoice->loadMissing(['items', 'order.items']),
                'created' => false,
            ];
        }

        $years = max(1, $years);
        [$currentRenewalDate, $nextRenewalDate] = $this->buildRenewalWindow($domain, $years);
        $quote = $this->buildRenewalQuote($domain, $years);

        $invoice = DB::transaction(function () use (
            $domain,
            $years,
            $autoGenerated,
            $currentRenewalDate,
            $nextRenewalDate,
            $quote
        ) {
            $lockedDomain = Domain::query()->lockForUpdate()->findOrFail($domain->id);
            $existingInvoice = $this->findPendingRenewalInvoice($lockedDomain);

            if ($existingInvoice instanceof Invoice) {
                return $existingInvoice->loadMissing(['items', 'order.items']);
            }

            $order = Order::create([
                'client_id' => $lockedDomain->client_id,
                'status' => Order::STATUS_PENDING,
                'type' => 'domain_renewal',
                'notes' => 'Domain renewal order for ' . $lockedDomain->domain_name,
            ]);

            $order->items()->create([
                'domain' => $lockedDomain->domain_name,
                'item_option' => 'renew',
                'price_cents' => $quote['price_cents'],
                'meta' => [
                    'currency' => $quote['currency'],
                    'registrar' => $lockedDomain->registrar ?: $this->defaultRegistrarType(),
                    'domain_id' => $lockedDomain->id,
                    'current_renewal_date' => $currentRenewalDate->toDateString(),
                    'renewal_date' => $nextRenewalDate->toDateString(),
                    'term_years' => $years,
                    'auto_generated' => $autoGenerated,
                ],
            ]);

            $invoice = Invoice::create([
                'client_id' => $lockedDomain->client_id,
                'order_id' => $order->id,
                'number' => $this->generateUniqueInvoiceNumber(),
                'status' => 'unpaid',
                'subtotal_cents' => $quote['price_cents'],
                'total_cents' => $quote['price_cents'],
                'currency' => $quote['currency'],
                'due_date' => $currentRenewalDate->toDateString(),
            ]);

            $invoice->items()->create([
                'item_type' => 'domain',
                'reference_id' => $lockedDomain->id,
                'description' => 'Domain Renewal: ' . $lockedDomain->domain_name,
                'qty' => 1,
                'unit_price_cents' => $quote['price_cents'],
                'total_cents' => $quote['price_cents'],
            ]);

            return $invoice->loadMissing(['items', 'order.items']);
        });

        return [
            'invoice' => $invoice,
            'created' => true,
        ];
    }

    public function processDueAutoRenewals(bool $dryRun = false): array
    {
        $summary = [
            'scanned' => 0,
            'due' => 0,
            'created' => 0,
            'existing' => 0,
            'renewed' => 0,
            'awaiting_payment' => 0,
            'failed' => 0,
        ];

        $domains = Domain::query()
            ->where('auto_renew', true)
            ->whereNotNull('renewal_date')
            ->whereIn('status', ['active', 'pending', 'expired'])
            ->with('client')
            ->orderBy('renewal_date')
            ->get();

        foreach ($domains as $domain) {
            $summary['scanned']++;

            if (!$this->isDueForAutoRenewal($domain)) {
                continue;
            }

            $summary['due']++;

            try {
                $checkout = $this->prepareRenewalCheckout($domain, 1, true);
                $invoice = $checkout['invoice'];

                if ($checkout['created']) {
                    $summary['created']++;
                } else {
                    $summary['existing']++;
                }

                if ($dryRun || $invoice->status === 'paid') {
                    continue;
                }

                if (strtolower((string) $domain->payment_method) !== 'mock_gateway') {
                    $domain->forceFill([
                        'dns_last_note' => 'Auto-renew invoice #' . $invoice->number . ' is ready and awaiting payment.',
                    ])->save();

                    $summary['awaiting_payment']++;
                    continue;
                }

                app(InvoiceSettlementService::class)->markPaid($invoice, 'mock_gateway');

                $domain->refresh();
                $domain->forceFill([
                    'dns_last_note' => null,
                ])->save();

                $summary['renewed']++;
            } catch (\Throwable $e) {
                Log::error('Auto-renew processing failed', [
                    'domain_id' => $domain->id,
                    'domain' => $domain->domain_name,
                    'error' => $e->getMessage(),
                ]);

                $domain->forceFill([
                    'dns_last_note' => 'Auto-renew failed: ' . Str::limit($e->getMessage(), 180),
                ])->save();

                $summary['failed']++;
            }
        }

        return $summary;
    }

    public function findPendingRenewalInvoice(Domain $domain): ?Invoice
    {
        return Invoice::query()
            ->where('client_id', $domain->client_id)
            ->whereIn('status', ['draft', 'unpaid'])
            ->where(function ($query) use ($domain) {
                $query->whereHas('order.items', function ($items) use ($domain) {
                    $items->where('domain', $domain->domain_name)
                        ->where('item_option', 'renew');
                })->orWhereHas('items', function ($items) use ($domain) {
                    $items->where('item_type', 'domain')
                        ->where('reference_id', $domain->id)
                        ->where('description', 'like', 'Domain Renewal:%');
                });
            })
            ->latest('id')
            ->first();
    }

    public function isDueForAutoRenewal(Domain $domain, ?Carbon $today = null): bool
    {
        if (!$domain->auto_renew || empty($domain->renewal_date)) {
            return false;
        }

        $today = ($today ?: now())->copy()->startOfDay();
        $renewalDate = Carbon::parse($domain->renewal_date)->startOfDay();
        $startDate = $renewalDate->copy()->subDays($this->leadDaysFor($domain));

        return $today->greaterThanOrEqualTo($startDate);
    }

    public function leadDaysFor(Domain $domain): int
    {
        $registrar = strtolower((string) ($domain->registrar ?: $this->defaultRegistrarType()));
        $tld = $this->extractTld($domain->domain_name);

        if ($registrar === 'enom') {
            return 30;
        }

        if (in_array($tld, [
            'ch',
            'es',
            'com.es',
            'nom.es',
            'org.es',
            'fr',
            'li',
            'pe',
            'com.pe',
            'net.pe',
            'org.pe',
            'sg',
            'com.sg',
            'com.au',
            'net.au',
            'org.au',
        ], true)) {
            return 12;
        }

        if (in_array($tld, ['cx', 'de', 'eu', 'nl'], true)) {
            return 5;
        }

        return 7;
    }

    protected function buildRenewalWindow(Domain $domain, int $years = 1): array
    {
        $currentRenewalDate = $domain->renewal_date
            ? Carbon::parse($domain->renewal_date)->startOfDay()
            : now()->startOfDay()->addYear();

        $nextRenewalDate = $currentRenewalDate->copy()->addYears(max(1, $years));

        return [$currentRenewalDate, $nextRenewalDate];
    }

    protected function buildRenewalQuote(Domain $domain, int $years = 1): array
    {
        $registrar = strtolower((string) ($domain->registrar ?: $this->defaultRegistrarType()));
        $tld = $this->extractTld($domain->domain_name);

        $row = DomainTld::query()
            ->with([
                'prices' => fn ($query) => $query
                    ->where('action', 'renew')
                    ->where('years', max(1, $years)),
            ])
            ->where('enabled', true)
            ->whereIn('tld', [$tld, '.' . $tld])
            ->whereHas('provider', function ($query) use ($registrar) {
                $query->active()->where('type', $registrar);
            })
            ->first();

        $price = $row?->prices->first()?->sale ?? $row?->prices->first()?->cost;
        $currency = $row?->currency ?: 'USD';

        if (!is_numeric($price)) {
            $price = $this->fallbackRenewalPrice($domain, $years);
        }

        return [
            'price_cents' => (int) round(((float) $price) * 100),
            'currency' => $currency,
        ];
    }

    protected function fallbackRenewalPrice(Domain $domain, int $years = 1): float
    {
        $tld = $this->extractTld($domain->domain_name);

        $row = DomainTld::query()
            ->with([
                'prices' => fn ($query) => $query
                    ->where('action', 'register')
                    ->where('years', max(1, $years)),
            ])
            ->where('enabled', true)
            ->whereIn('tld', [$tld, '.' . $tld])
            ->first();

        $price = $row?->prices->first()?->sale ?? $row?->prices->first()?->cost;

        if (is_numeric($price)) {
            return (float) $price;
        }

        return 10.0 * max(1, $years);
    }

    protected function extractTld(string $domainName): string
    {
        $normalized = strtolower(trim($domainName));

        if (!str_contains($normalized, '.')) {
            return '';
        }

        $parts = explode('.', $normalized, 2);

        return ltrim($parts[1] ?? '', '.');
    }

    protected function defaultRegistrarType(): string
    {
        return DomainProvider::query()
            ->active()
            ->whereIn('type', ['namecheap', 'enom'])
            ->orderByRaw("CASE WHEN type = 'namecheap' THEN 0 WHEN type = 'enom' THEN 1 ELSE 2 END")
            ->value('type') ?? 'namecheap';
    }

    protected function generateUniqueInvoiceNumber(): string
    {
        do {
            $number = 'INV-' . Str::upper(Str::random(6));
        } while (Invoice::where('number', $number)->exists());

        return $number;
    }
}
