<?php

namespace App\Services\Domains;

use App\Models\Domain;
use App\Models\DomainProvider;
use App\Models\DomainTld;
use App\Models\Invoice;
use App\Models\Order;
use App\Services\Domains\Exceptions\MissingDomainProviderException;
use App\Services\Domains\Exceptions\MissingRenewalPriceException;
use Carbon\Carbon;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Str;

class DomainRenewalService
{
    public function prepareRenewalCheckout(Domain $domain, int $years = 1, bool $autoGenerated = false): array
    {
        $domain->loadMissing('client');

        if (!$autoGenerated) {
            $existingInvoice = $this->findPendingRenewalInvoice($domain);
            if ($existingInvoice instanceof Invoice) {
                return [
                    'invoice' => $existingInvoice->loadMissing(['items', 'order.items']),
                    'created' => false,
                    'eligible' => true,
                ];
            }
        }

        $years = max(1, $years);

        return DB::transaction(function () use (
            $domain,
            $years,
            $autoGenerated,
        ) {
            $lockedDomain = Domain::query()->lockForUpdate()->findOrFail($domain->id);

            if ($autoGenerated && !$this->isDueForAutoRenewal($lockedDomain)) {
                return [
                    'invoice' => null,
                    'created' => false,
                    'eligible' => false,
                ];
            }

            $existingInvoice = $this->findPendingRenewalInvoice($lockedDomain);

            if ($existingInvoice instanceof Invoice) {
                return [
                    'invoice' => $existingInvoice->loadMissing(['items', 'order.items']),
                    'created' => false,
                    'eligible' => true,
                ];
            }

            [$currentRenewalDate, $nextRenewalDate] = $this->buildRenewalWindow($lockedDomain, $years);
            $quote = $this->buildRenewalQuote($lockedDomain, $years);

            $order = Order::create([
                'client_id' => $lockedDomain->client_id,
                'status' => Order::STATUS_PENDING,
                'type' => 'domain_renewal',
                'notes' => 'Domain renewal order for ' . $lockedDomain->domain_name,
            ]);

            $order->items()->create([
                'domain' => $lockedDomain->domain_name,
                'item_option' => 'renew',
                'price_cents' => $quote['price_cents'],
                'meta' => [
                    'currency' => $quote['currency'],
                    'registrar' => $quote['provider_type'],
                    'provider_id' => $quote['provider_id'],
                    'provider_type' => $quote['provider_type'],
                    'provider_mode' => $quote['provider_mode'],
                    'domain_id' => $lockedDomain->id,
                    'current_renewal_date' => $currentRenewalDate->toDateString(),
                    'renewal_date' => $nextRenewalDate->toDateString(),
                    'term_years' => $years,
                    'auto_generated' => $autoGenerated,
                ],
            ]);

            $invoice = Invoice::create([
                'client_id' => $lockedDomain->client_id,
                'order_id' => $order->id,
                'number' => $this->generateUniqueInvoiceNumber(),
                'status' => 'unpaid',
                'subtotal_cents' => $quote['price_cents'],
                'total_cents' => $quote['price_cents'],
                'currency' => $quote['currency'],
                'due_date' => $currentRenewalDate->toDateString(),
            ]);

            $invoice->items()->create([
                'item_type' => 'domain',
                'reference_id' => $lockedDomain->id,
                'description' => 'Domain Renewal: ' . $lockedDomain->domain_name,
                'qty' => 1,
                'unit_price_cents' => $quote['price_cents'],
                'total_cents' => $quote['price_cents'],
            ]);

            return [
                'invoice' => $invoice->loadMissing(['items', 'order.items']),
                'created' => true,
                'eligible' => true,
            ];
        });
    }

    public function processDueAutoRenewals(bool $dryRun = false): array
    {
        $summary = [
            'scanned' => 0,
            'due' => 0,
            'created' => 0,
            'existing' => 0,
            'renewed' => 0,
            'awaiting_payment' => 0,
            'failed' => 0,
            'details' => [],
        ];

        $domains = Domain::query()
            ->where('auto_renew', true)
            ->whereNotNull('renewal_date')
            ->whereIn('status', ['active', 'pending', 'expired'])
            ->with('client')
            ->orderBy('renewal_date')
            ->get();

        foreach ($domains as $domain) {
            $summary['scanned']++;

            if (!$this->isDueForAutoRenewal($domain)) {
                continue;
            }

            $summary['due']++;

            try {
                if ($dryRun) {
                    $pendingInvoice = $this->findPendingRenewalInvoice($domain);
                    $quote = $this->buildRenewalQuote($domain, 1);

                    $summary['details'][] = [
                        'domain' => $domain->domain_name,
                        'renewal_date' => Carbon::parse($domain->renewal_date)->toDateString(),
                        'provider' => $quote['provider_type'],
                        'estimated_price_cents' => $quote['price_cents'],
                        'currency' => $quote['currency'],
                        'pending_invoice' => $pendingInvoice instanceof Invoice,
                        'action' => $pendingInvoice instanceof Invoice
                            ? 'awaiting_payment'
                            : 'create_unpaid_invoice',
                    ];

                    continue;
                }

                $checkout = $this->prepareRenewalCheckout($domain, 1, true);

                if (!($checkout['eligible'] ?? true)) {
                    continue;
                }

                $invoice = $checkout['invoice'];

                if ($checkout['created']) {
                    $summary['created']++;
                } else {
                    $summary['existing']++;
                }

                $awaitingPaymentMessage = strtr(
                    t(
                        'client.domains.auto_renew_invoice_awaiting_payment',
                        'Auto-renew invoice #:invoice is ready and awaiting payment.'
                    ),
                    [':invoice' => $invoice->number],
                );

                $domain->forceFill([
                    'dns_last_note' => $awaitingPaymentMessage,
                ])->save();

                $summary['awaiting_payment']++;
            } catch (MissingRenewalPriceException $e) {
                $registrar = strtolower((string) ($domain->registrar ?: $this->defaultRegistrarType()));
                $tld = $this->extractTld($domain->domain_name);
                $reason = $e instanceof MissingDomainProviderException
                    ? 'domain_provider_missing'
                    : 'missing_renewal_sale';

                Log::warning('Auto-renew skipped: no trusted renewal price for domain.', [
                    'domain_id' => $domain->id,
                    'domain' => $domain->domain_name,
                    'registrar' => $registrar,
                    'tld' => $tld,
                    'reason' => $reason,
                    'error' => $e->getMessage(),
                ]);

                if (!$dryRun) {
                    $domain->forceFill([
                        'dns_last_note' => $reason === 'domain_provider_missing'
                            ? t(
                                'client.domains.auto_renew_provider_unavailable',
                                'Auto-renew skipped: this domain has no trusted registrar provider configured.'
                            )
                            : t(
                                'client.domains.auto_renew_price_unavailable',
                                'Auto-renew skipped: no trusted renewal price (sale) is currently available for this domain.'
                            ),
                    ])->save();
                }

                $summary['failed']++;
            } catch (\Throwable $e) {
                Log::error('Auto-renew processing failed', [
                    'domain_id' => $domain->id,
                    'domain' => $domain->domain_name,
                    'error' => $e->getMessage(),
                ]);

                if (!$dryRun) {
                    $failureMessage = strtr(
                        t(
                            'client.domains.auto_renew_invoice_failed',
                            'Auto-renew invoice preparation failed: :error'
                        ),
                        [':error' => Str::limit($e->getMessage(), 180)],
                    );

                    $domain->forceFill([
                        'dns_last_note' => $failureMessage,
                    ])->save();
                }

                $summary['failed']++;
            }
        }

        return $summary;
    }

    public function findPendingRenewalInvoice(Domain $domain): ?Invoice
    {
        return Invoice::query()
            ->where('client_id', $domain->client_id)
            ->whereIn('status', ['draft', 'unpaid'])
            ->where(function ($query) use ($domain) {
                $query->whereHas('order.items', function ($items) use ($domain) {
                    $items->where('domain', $domain->domain_name)
                        ->where('item_option', 'renew');
                })->orWhereHas('items', function ($items) use ($domain) {
                    $items->where('item_type', 'domain')
                        ->where('reference_id', $domain->id)
                        ->where('description', 'like', 'Domain Renewal:%');
                });
            })
            ->latest('id')
            ->first();
    }

    public function isDueForAutoRenewal(Domain $domain, ?Carbon $today = null): bool
    {
        if (!$domain->auto_renew || empty($domain->renewal_date)) {
            return false;
        }

        $today = ($today ?: now())->copy()->startOfDay();
        $renewalDate = Carbon::parse($domain->renewal_date)->startOfDay();
        $startDate = $renewalDate->copy()->subDays($this->leadDaysFor($domain));

        return $today->greaterThanOrEqualTo($startDate);
    }

    public function leadDaysFor(Domain $domain): int
    {
        $registrar = strtolower((string) ($domain->registrar ?: $this->defaultRegistrarType()));
        $tld = $this->extractTld($domain->domain_name);

        if ($registrar === 'enom') {
            return 30;
        }

        if (in_array($tld, [
            'ch',
            'es',
            'com.es',
            'nom.es',
            'org.es',
            'fr',
            'li',
            'pe',
            'com.pe',
            'net.pe',
            'org.pe',
            'sg',
            'com.sg',
            'com.au',
            'net.au',
            'org.au',
        ], true)) {
            return 12;
        }

        if (in_array($tld, ['cx', 'de', 'eu', 'nl'], true)) {
            return 5;
        }

        return 7;
    }

    protected function buildRenewalWindow(Domain $domain, int $years = 1): array
    {
        $currentRenewalDate = $domain->renewal_date
            ? Carbon::parse($domain->renewal_date)->startOfDay()
            : now()->startOfDay()->addYear();

        $nextRenewalDate = $currentRenewalDate->copy()->addYears(max(1, $years));

        return [$currentRenewalDate, $nextRenewalDate];
    }

    /**
     * TLD-3B/TLD-3D — Strict Sale-Only, Exact-Provider-Identity Renewal Pricing.
     *
     * TLD-3D — Hybrid Provider Identity: Domain.provider_id (when present) is the ONLY source
     * of truth used to resolve the provider for managed renewal pricing. There is no lookup by
     * Domain.registrar's type string anymore, no defaultRegistrarType() fallback, and no
     * cross-type substitution — closing the pricing-vs-provisioning drift confirmed by TLD-3C.
     * A null Domain.provider_id represents a legitimate external/unmanaged domain (manual
     * admin/client "quick add" — TLD-3D audit section 13/16); managed renewal pricing must
     * fail safely for it via MissingDomainProviderException, never guess a provider.
     *
     * Once a provider is resolved this way, it must still be active, and the matching
     * DomainTld row (enabled, same tld, same exact provider_id) must carry an explicit,
     * numeric, > 0 renew.sale and a valid ISO-like currency — no renew.cost, no register.sale,
     * no register.cost, no hard-coded fallback (TLD-3B contract, unchanged). Any failure throws
     * — never a synthetic price.
     */
    protected function buildRenewalQuote(Domain $domain, int $years = 1): array
    {
        $years = max(1, $years);

        if ($domain->provider_id === null) {
            throw new MissingDomainProviderException(sprintf(
                'Domain [%s] has no trusted provider identity (provider_id is null — external/unmanaged domain); managed renewal pricing is not available.',
                $domain->domain_name,
            ));
        }

        $provider = DomainProvider::query()->whereKey($domain->provider_id)->first();

        if (!$provider instanceof DomainProvider || !$provider->is_active) {
            throw new MissingDomainProviderException(sprintf(
                'Domain [%s] trusted provider_id [%s] is missing or inactive.',
                $domain->domain_name,
                (string) $domain->provider_id,
            ));
        }

        $tld = $this->extractTld($domain->domain_name);

        $row = DomainTld::query()
            ->with([
                'prices' => fn ($query) => $query
                    ->where('action', 'renew')
                    ->where('years', $years),
            ])
            ->where('enabled', true)
            ->whereIn('tld', [$tld, '.' . $tld])
            ->where('provider_id', $provider->getKey())
            ->first();

        $sale = $row?->prices->first()?->sale;

        if ($sale === null || $sale === '' || !is_numeric($sale) || (float) $sale <= 0) {
            throw new MissingRenewalPriceException(sprintf(
                'Missing trusted renew.sale price for domain [%s], tld [%s], provider_id [%d], years [%d].',
                $domain->domain_name,
                $tld,
                $provider->getKey(),
                $years,
            ));
        }

        $currency = strtoupper(trim((string) ($row->currency ?? '')));

        if ($currency === '' || !preg_match('/^[A-Z]{3}$/', $currency)) {
            throw new MissingRenewalPriceException(sprintf(
                'Invalid or missing renewal currency for domain [%s], tld [%s], provider_id [%d].',
                $domain->domain_name,
                $tld,
                $provider->getKey(),
            ));
        }

        return [
            'price_cents' => (int) round(((float) $sale) * 100),
            'currency' => $currency,
            'provider_id' => $provider->getKey(),
            'provider_type' => strtolower((string) $provider->type),
            'provider_mode' => strtolower((string) $provider->mode),
        ];
    }

    protected function extractTld(string $domainName): string
    {
        $normalized = strtolower(trim($domainName));

        if (!str_contains($normalized, '.')) {
            return '';
        }

        $parts = explode('.', $normalized, 2);

        return ltrim($parts[1] ?? '', '.');
    }

    protected function defaultRegistrarType(): string
    {
        return DomainProvider::query()
            ->active()
            ->whereIn('type', ['namecheap', 'enom'])
            ->orderByRaw("CASE WHEN type = 'namecheap' THEN 0 WHEN type = 'enom' THEN 1 ELSE 2 END")
            ->value('type') ?? 'namecheap';
    }

    protected function generateUniqueInvoiceNumber(): string
    {
        do {
            $number = 'INV-' . Str::upper(Str::random(6));
        } while (Invoice::where('number', $number)->exists());

        return $number;
    }
}
