<?php

namespace App\Services\Tenancy;

use App\Models\Tenancy\Subscription;
use App\Support\Tenancy\TenantThemeSettings;
use Illuminate\Support\Facades\Storage;

/**
 * Generates and manages the per-tenant theme CSS file.
 *
 * Output file  : storage/app/public/tenant-themes/{subscription_id}.css
 * Public URL   : {APP_URL}/storage/tenant-themes/{subscription_id}.css
 *
 * The generated file defines CSS custom properties on :root and
 * utility classes (bg-theme-*, text-theme-*, btn-theme-*) that
 * section templates can consume.
 */
class TenantThemeCssGenerator
{
    private const DISK = 'public';
    private const DIRECTORY = 'tenant-themes';

    // -----------------------------------------------------------------------
    // Public API
    // -----------------------------------------------------------------------

    /**
     * Regenerate the CSS file for the given subscription.
     * Creates the directory if it does not exist.
     */
    public function generate(Subscription $subscription): string
    {
        $theme = TenantThemeSettings::fromArray(
            is_array($subscription->theme_settings) ? $subscription->theme_settings : []
        );

        $css = $this->buildCss($theme);

        Storage::disk(self::DISK)->put($this->relativePath($subscription->id), $css);

        return $css;
    }

    /**
     * Delete the CSS file for a subscription (e.g. on subscription deletion).
     */
    public function delete(int $subscriptionId): void
    {
        $path = $this->relativePath($subscriptionId);

        if (Storage::disk(self::DISK)->exists($path)) {
            Storage::disk(self::DISK)->delete($path);
        }
    }

    /**
     * Absolute filesystem path (useful for artisan commands / tests).
     */
    public function absolutePath(int $subscriptionId): string
    {
        return Storage::disk(self::DISK)->path($this->relativePath($subscriptionId));
    }

    /**
     * Public URL to the CSS file, or null if the file does not exist.
     */
    public function urlIfExists(int $subscriptionId): ?string
    {
        $path = $this->relativePath($subscriptionId);

        if (! Storage::disk(self::DISK)->exists($path)) {
            return null;
        }

        return Storage::disk(self::DISK)->url($path);
    }

    /**
     * Public URL (unconditional — use when you know the file exists or for
     * injecting into layouts after generation).
     */
    public function url(int $subscriptionId): string
    {
        return Storage::disk(self::DISK)->url($this->relativePath($subscriptionId));
    }

    /**
     * Static helper for Blade views and controllers.
     *
     * Returns the public URL to the generated tenant theme CSS file
     * if it exists, or null if the file has not been generated yet
     * or if no subscription is provided.
     *
     * Usage in Blade:
     *   @php $themeUrl = \App\Services\Tenancy\TenantThemeCssGenerator::publicUrlFor($subscription); @endphp
     *   @if ($themeUrl) <link rel="stylesheet" href="{{ $themeUrl }}"> @endif
     */
    public static function publicUrlFor(?Subscription $subscription): ?string
    {
        if ($subscription === null || ! isset($subscription->id)) {
            return null;
        }

        $path = self::DIRECTORY . '/' . $subscription->id . '.css';

        if (! Storage::disk(self::DISK)->exists($path)) {
            return null;
        }

        return Storage::disk(self::DISK)->url($path);
    }

    // -----------------------------------------------------------------------
    // Internal helpers
    // -----------------------------------------------------------------------

    private function relativePath(int $subscriptionId): string
    {
        return self::DIRECTORY . '/' . $subscriptionId . '.css';
    }

    private function buildCss(TenantThemeSettings $t): string
    {
        $lines = [];

        // ------------------------------------------------------------------
        // 1. CSS custom properties (:root)
        // ------------------------------------------------------------------
        $lines[] = '/* Tenant theme — generated by TenantThemeCssGenerator */';
        $lines[] = ':root {';

        // Colors
        $lines[] = "  /* --- Colors --- */";
        $lines[] = "  --theme-color-primary:   {$t->colorPrimary};";
        $lines[] = "  --theme-color-secondary: {$t->colorSecondary};";
        $lines[] = "  --theme-color-surface:   {$t->colorSurface};";
        $lines[] = "  --theme-color-muted:     {$t->colorMuted};";
        $lines[] = "  --theme-color-heading:   {$t->colorHeading};";
        $lines[] = "  --theme-color-body:      {$t->colorBody};";
        $lines[] = "  --theme-color-border:    {$t->colorBorder};";

        // Typography
        $lines[] = "";
        $lines[] = "  /* --- Typography --- */";
        $lines[] = "  --theme-font-primary:    {$t->fontPrimary};";
        $lines[] = "  --theme-font-heading:    {$t->fontHeading};";
        $lines[] = "  --theme-font-size-base:  {$t->baseFontSize};";
        $lines[] = "  --theme-weight-normal:   {$t->weightNormal};";
        $lines[] = "  --theme-weight-bold:     {$t->weightBold};";

        // Shape
        $lines[] = "";
        $lines[] = "  /* --- Shape / Radius --- */";
        $lines[] = "  --theme-radius-sm:       {$t->radiusSm};";
        $lines[] = "  --theme-radius-md:       {$t->radiusMd};";
        $lines[] = "  --theme-radius-lg:       {$t->radiusLg};";
        $lines[] = "  --theme-radius-xl:       {$t->radiusXl};";

        // Buttons — style token
        $lines[] = "";
        $lines[] = "  /* --- Buttons --- */";
        $lines[] = "  --theme-button-radius:       {$t->buttonRadius};";

        // Buttons — explicit color tokens
        // These are the primary source of truth for button colors.
        // They intentionally default to the primary color values so that
        // existing subscriptions that have not saved these tokens yet
        // render identically to the previous behaviour.
        $lines[] = "  --theme-button-bg:           {$t->buttonBgColor};";
        $lines[] = "  --theme-button-text:         {$t->buttonTextColor};";
        $lines[] = "  --theme-button-hover-bg:     {$t->buttonHoverBgColor};";
        $lines[] = "  --theme-button-hover-text:   {$t->buttonHoverTextColor};";

        $lines[] = '}';
        $lines[] = '';

        // ------------------------------------------------------------------
        // 2. Semantic utility classes (background)
        // ------------------------------------------------------------------
        $lines[] = '/* --- Background utilities --- */';
        $lines[] = '.bg-theme-primary   { background-color: var(--theme-color-primary) !important; }';
        $lines[] = '.bg-theme-secondary { background-color: var(--theme-color-secondary) !important; }';
        $lines[] = '.bg-theme-surface   { background-color: var(--theme-color-surface) !important; }';
        $lines[] = '.bg-theme-muted     { background-color: var(--theme-color-muted) !important; }';
        $lines[] = '';

        // ------------------------------------------------------------------
        // 3. Semantic utility classes (text)
        // ------------------------------------------------------------------
        $lines[] = '/* --- Text utilities --- */';
        $lines[] = '.text-theme-primary   { color: var(--theme-color-primary) !important; }';
        $lines[] = '.text-theme-secondary { color: var(--theme-color-secondary) !important; }';
        $lines[] = '.text-theme-heading   { color: var(--theme-color-heading) !important; }';
        $lines[] = '.text-theme-body      { color: var(--theme-color-body) !important; }';
        $lines[] = '.text-theme-muted     { color: var(--theme-color-muted) !important; }';
        $lines[] = '';

        // ------------------------------------------------------------------
        // 4. Border utilities
        // ------------------------------------------------------------------
        $lines[] = '/* --- Border utilities --- */';
        $lines[] = '.border-theme-primary { border-color: var(--theme-color-primary) !important; }';
        $lines[] = '.border-theme-border  { border-color: var(--theme-color-border) !important; }';
        $lines[] = '';

        // ------------------------------------------------------------------
        // 5. Button utilities
        //
        // All button styles now use the explicit --theme-button-* color tokens
        // rather than colour_primary / color_secondary directly.
        //
        // button_style controls the border treatment (filled / outline / ghost);
        // button_bg_color / button_text_color / hover variants control the paint.
        //
        // .btn-theme-secondary is kept for backwards compatibility but mirrors
        // the same token-driven approach.
        // ------------------------------------------------------------------
        $lines[] = '/* --- Button utilities --- */';

        // Shared typography / shape declarations (same for all styles)
        $sharedProps = implode("\n", [
            '  display: inline-flex; align-items: center; justify-content: center;',
            '  border-radius: var(--theme-button-radius);',
            '  font-family: var(--theme-font-primary);',
            '  font-weight: var(--theme-weight-bold);',
            '  padding: 0.625rem 1.5rem;',
            '  cursor: pointer; text-decoration: none;',
        ]);

        if ($t->buttonStyle === 'filled') {
            // ── Filled ─────────────────────────────────────────────────────
            $lines[] = '.btn-theme-primary {';
            $lines[] = $sharedProps;
            $lines[] = '  background-color: var(--theme-button-bg);';
            $lines[] = '  color: var(--theme-button-text);';
            $lines[] = '  border: 2px solid transparent;';
            $lines[] = '  transition: background-color 0.15s ease, color 0.15s ease, transform 0.1s ease;';
            $lines[] = '}';
            $lines[] = '.btn-theme-primary:hover {';
            $lines[] = '  background-color: var(--theme-button-hover-bg);';
            $lines[] = '  color: var(--theme-button-hover-text);';
            $lines[] = '}';
            $lines[] = '.btn-theme-primary:active { transform: scale(0.97); }';

            $lines[] = '';
            $lines[] = '.btn-theme-secondary {';
            $lines[] = $sharedProps;
            $lines[] = '  background-color: var(--theme-color-secondary);';
            $lines[] = '  color: #ffffff;';
            $lines[] = '  border: 2px solid transparent;';
            $lines[] = '  transition: opacity 0.15s ease, transform 0.1s ease;';
            $lines[] = '}';
            $lines[] = '.btn-theme-secondary:hover { opacity: 0.88; }';
            $lines[] = '.btn-theme-secondary:active { transform: scale(0.97); }';

        } elseif ($t->buttonStyle === 'outline') {
            // ── Outline ────────────────────────────────────────────────────
            $lines[] = '.btn-theme-primary {';
            $lines[] = $sharedProps;
            $lines[] = '  background-color: transparent;';
            $lines[] = '  color: var(--theme-button-bg);';
            $lines[] = '  border: 2px solid var(--theme-button-bg);';
            $lines[] = '  transition: background-color 0.15s ease, color 0.15s ease, transform 0.1s ease;';
            $lines[] = '}';
            $lines[] = '.btn-theme-primary:hover {';
            $lines[] = '  background-color: var(--theme-button-hover-bg);';
            $lines[] = '  color: var(--theme-button-hover-text);';
            $lines[] = '  border-color: var(--theme-button-hover-bg);';
            $lines[] = '}';
            $lines[] = '.btn-theme-primary:active { transform: scale(0.97); }';

            $lines[] = '';
            $lines[] = '.btn-theme-secondary {';
            $lines[] = $sharedProps;
            $lines[] = '  background-color: transparent;';
            $lines[] = '  color: var(--theme-color-secondary);';
            $lines[] = '  border: 2px solid var(--theme-color-secondary);';
            $lines[] = '  transition: background-color 0.15s ease, color 0.15s ease, transform 0.1s ease;';
            $lines[] = '}';
            $lines[] = '.btn-theme-secondary:hover { background-color: var(--theme-color-secondary); color: #ffffff; }';
            $lines[] = '.btn-theme-secondary:active { transform: scale(0.97); }';

        } else {
            // ── Ghost ──────────────────────────────────────────────────────
            $lines[] = '.btn-theme-primary {';
            $lines[] = $sharedProps;
            $lines[] = '  background-color: transparent;';
            $lines[] = '  color: var(--theme-button-bg);';
            $lines[] = '  border: 2px solid transparent;';
            $lines[] = '  transition: background-color 0.15s ease, color 0.15s ease, transform 0.1s ease;';
            $lines[] = '}';
            $lines[] = '.btn-theme-primary:hover {';
            $lines[] = '  background-color: color-mix(in srgb, var(--theme-button-hover-bg) 12%, transparent);';
            $lines[] = '  color: var(--theme-button-hover-text);';
            $lines[] = '}';
            $lines[] = '.btn-theme-primary:active { transform: scale(0.97); }';

            $lines[] = '';
            $lines[] = '.btn-theme-secondary {';
            $lines[] = $sharedProps;
            $lines[] = '  background-color: transparent;';
            $lines[] = '  color: var(--theme-color-secondary);';
            $lines[] = '  border: 2px solid transparent;';
            $lines[] = '  transition: background-color 0.15s ease, transform 0.1s ease;';
            $lines[] = '}';
            $lines[] = '.btn-theme-secondary:hover { background-color: color-mix(in srgb, var(--theme-color-secondary) 10%, transparent); }';
            $lines[] = '.btn-theme-secondary:active { transform: scale(0.97); }';
        }

        $lines[] = '';

        // ------------------------------------------------------------------
        // 6. Typography base
        // ------------------------------------------------------------------
        $lines[] = '/* --- Typography base --- */';
        $lines[] = '.font-theme-primary { font-family: var(--theme-font-primary) !important; }';
        $lines[] = '.font-theme-body    { font-family: var(--theme-font-primary) !important; }';
        $lines[] = '.font-theme-heading { font-family: var(--theme-font-heading) !important; }';
        $lines[] = '';

        // ------------------------------------------------------------------
        // 7. Radius utilities
        // ------------------------------------------------------------------
        $lines[] = '/* --- Radius utilities --- */';
        $lines[] = '.rounded-theme-sm { border-radius: var(--theme-radius-sm) !important; }';
        $lines[] = '.rounded-theme-md { border-radius: var(--theme-radius-md) !important; }';
        $lines[] = '.rounded-theme-lg { border-radius: var(--theme-radius-lg) !important; }';
        $lines[] = '.rounded-theme-xl { border-radius: var(--theme-radius-xl) !important; }';
        $lines[] = '';

        return implode("\n", $lines);
    }
}
