<?php

namespace App\Support\AdminBrand;

use App\Models\GeneralSetting;
use Illuminate\Support\Facades\Storage;

/**
 * Generates and manages the global Admin Brand CSS file.
 *
 * Output (Storage disk 'public'):
 *   storage/app/public/admin-theme/admin-brand.css
 *
 * Public URL (after `php artisan storage:link`):
 *   {APP_URL}/storage/admin-theme/admin-brand.css
 *
 * The generated file defines CSS custom properties on :root:
 *   --admin-color-primary      ← resolves --color-purple-brand
 *   --admin-color-secondary    ← resolves --color-red-brand
 *   --admin-color-muted        ← resolves --color-gray-light
 *   --admin-color-body         ← resolves --color-gray-dark
 *   --admin-color-custom-1…5   ← reserved for DesignTokenRegistry Phase 2
 *
 * Loading order in head.blade.php:
 *   1. app.css           — defines @theme aliases with var(--admin-color-*, fallback)
 *   2. admin-brand.css   — defines --admin-color-* (this file)
 *   3. tenant-theme.css  — defines --theme-color-* (per subscription)
 */
class AdminBrandCssGenerator
{
    private const DISK      = 'public';
    private const DIRECTORY = 'admin-theme';
    private const FILE      = 'admin-brand.css';

    // ── Public API ────────────────────────────────────────────────────────────

    /**
     * Generate (or re-generate) the admin-brand.css file from the given settings.
     *
     * Call this after saving admin_brand_settings to GeneralSetting.
     */
    public function generate(AdminBrandThemeSettings $settings): void
    {
        $css = $this->buildCss($settings);
        Storage::disk(self::DISK)->put(self::relativePath(), $css);
    }

    /**
     * Generate using the current admin_brand_settings from DB.
     * Falls back to defaults if no settings have been saved yet.
     */
    public function generateFromDb(): void
    {
        try {
            $row  = GeneralSetting::query()->first();
            $data = is_array($row?->admin_brand_settings ?? null)
                ? $row->admin_brand_settings
                : [];
        } catch (\Throwable) {
            $data = [];
        }

        $this->generate(AdminBrandThemeSettings::fromArray($data));
    }

    /**
     * Generate using default colours only if the CSS file does not exist yet.
     * Safe to call from AppServiceProvider::boot() — swallows all errors.
     */
    public static function generateIfMissing(): void
    {
        try {
            if (! Storage::disk(self::DISK)->exists(self::relativePath())) {
                (new self())->generateFromDb();
            }
        } catch (\Throwable) {
            // Silently ignore — CSS fallbacks in app.css handle missing file.
        }
    }

    /**
     * Delete the admin-brand.css file (e.g. for testing backward compatibility).
     */
    public static function delete(): void
    {
        try {
            if (Storage::disk(self::DISK)->exists(self::relativePath())) {
                Storage::disk(self::DISK)->delete(self::relativePath());
            }
        } catch (\Throwable) {
        }
    }

    /**
     * Public URL to admin-brand.css, or null if the file does not exist.
     *
     * Returns null when the file is absent → head.blade.php skips the tag →
     * app.css CSS var() fallbacks take over (backward-compatible).
     */
    public static function publicUrl(): ?string
    {
        try {
            if (! Storage::disk(self::DISK)->exists(self::relativePath())) {
                return null;
            }

            return Storage::disk(self::DISK)->url(self::relativePath());
        } catch (\Throwable) {
            return null;
        }
    }

    // ── CSS builder ───────────────────────────────────────────────────────────

    public function buildCss(AdminBrandThemeSettings $t): string
    {
        $lines = [];
        $lines[] = '/* Admin Brand Theme — generated by AdminBrandCssGenerator */';
        $lines[] = '/* Do not edit manually — regenerated on each admin save.  */';
        $lines[] = ':root {';
        $lines[] = '';
        $lines[] = '  /* ── Core brand tokens ──────────────────────────────── */';
        $lines[] = "  --admin-color-primary:   {$t->primary};";
        $lines[] = "  --admin-color-secondary: {$t->secondary};";
        $lines[] = "  --admin-color-muted:     {$t->muted};";
        $lines[] = "  --admin-color-body:      {$t->body};";
        $lines[] = '';
        $lines[] = '  /* ── Custom color slots (reserved for DesignTokenRegistry Phase 2) ── */';

        foreach ([1 => $t->custom1, 2 => $t->custom2, 3 => $t->custom3, 4 => $t->custom4, 5 => $t->custom5] as $n => $value) {
            if ($value !== '') {
                $lines[] = "  --admin-color-custom-{$n}: {$value};";
            }
        }

        $lines[] = '}';

        return implode("\n", $lines) . "\n";
    }

    // ── Internal helpers ──────────────────────────────────────────────────────

    private static function relativePath(): string
    {
        return self::DIRECTORY . '/' . self::FILE;
    }
}
